### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by martinvivek** [junpataleta/moodle-mod_threesixo#2] opened 2018-01-23 12:08 UTC
Did you remember to make the first column something unique in your call to get_records? Duplicate value '595' found in column 'userid'.
line 1199 of \lib\dml\mysqli_native_moodle_database.php: call to debugging()
line 530 of \mod\threesixo\classes\api.php: call to mysqli_native_moodle_database->get_records_sql()
line 65 of \mod\threesixo\report.php: call to mod_threesixo\api::get_participants()

Did you remember to make the first column something unique in your call to get_records? Duplicate value '1821' found in column 'userid'.
line 1199 of \lib\dml\mysqli_native_moodle_database.php: call to debugging()
line 530 of \mod\threesixo\classes\api.php: call to mysqli_native_moodle_database->get_records_sql()
line 65 of \mod\threesixo\report.php: call to mod_threesixo\api::get_participants()

**Comment by junpataleta** [comment] 2018-01-23 14:20
Hi Martin, 

Thanks for reporting this issue. It would be nice if you could provide instructions on how to reproduce this error. It would also make this issue easier to work on.

Thanks!

**Comment by martinvivek** [comment] 2018-01-23 15:04
Downloaded the plugin from Moodle (not from Github)
 Installed the plugin 
Created an activity with the name testing 
selected the participants as student 
remaining as default.
Click on a user found this error.

**Comment by junpataleta** [comment] 2018-01-24 15:57
Hi Martin,

Sorry, but I am still unable to replicate this issue. Perhaps providing details about your course and the activity would help. Information such as course settings, user enrolments, group settings and the 360 feedback activity settings could probably help pinpoint the cause of the problem.

**Comment by martinvivek** [comment] 2018-01-26 14:28
I have two enrolment method('manual' and 'auto'), users in both enrolments and showing duplicate and causing this error.

**Comment by junpataleta** [comment] 2018-01-28 05:03
Aha, thanks for that info. That certainly helped lock things down. I fixed it in https://github.com/junpataleta/moodle-mod_threesixo/commit/4e87c77e96c5b8a758f4a9f4859b69689bcb908f. Closing this.

**Closed by junpataleta** 2018-01-28 05:03 UTC
